String
ANIMATED_SPLASH = '/SplashScreen',
HOME_SCREEN = '/HomeScreen',
MOVIE_CONTAINER_SCREEN = '/MovieScreen',
TVSHOW_CONTAINER_SCREEN = '/TVShowScreen',
PEOPLE_CONTAINER_SCREEN = '/PeopleScreen',
DETAILS_CONTAINER_SCREEN = '/DetailsScreen'
;
